trigger:
  branches:
    include:
      - lab5_model_training

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_SUBSCRIPTION: SC-UDST-CCIT-DSAI3202-1
  RESOURCE_GROUP: Project
  WORKSPACE_NAME: 60300832-test

steps:
- checkout: self

- task: AzureCLI@2
  displayName: "Submit Azure ML Training Job"
  inputs:
    azureSubscription: $(AZURE_SUBSCRIPTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Ensuring Azure ML CLI extension is installed"
      az extension add -n ml -y || az extension update -n ml

      echo "Setting Azure ML defaults"
      az configure --defaults \
        group=$(RESOURCE_GROUP) \
        workspace=$(WORKSPACE_NAME)

      echo "Submitting Azure ML job"
      az ml job create --file lab5/jobs/train_job.yml