name: amazon-review-training-env

channels:
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - joblib
      - mlflow
      - azureml-mlflow
      - azureml-core   