$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

compute: azureml:cpu-cluster-2

inputs:
  sampled_data:
    type: uri_folder
    path: azureml:amazon_electronics_features_v1_sampled@latest

jobs:
  split:
    type: command
    component: azureml:split_dataset@latest
    inputs:
      data: ${{parent.inputs.sampled_data}}

  normalize_train:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.train}}

  normalize_val:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.val}}

  normalize_test:
    type: command
    component: azureml:normalize_text@latest
    inputs:
      data: ${{parent.jobs.split.outputs.test}}

  length_train:
    type: command
    component: azureml:length_features@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}

  sentiment_train:
    type: command
    component: azureml:sentiment_features@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}

  tfidf:
    type: command
    component: azureml:tfidf_features@latest
    inputs:
      train: ${{parent.jobs.normalize_train.outputs.out}}
      val: ${{parent.jobs.normalize_val.outputs.out}}
      test: ${{parent.jobs.normalize_test.outputs.out}}

  sbert_train:
    type: command
    component: azureml:sbert_embeddings@latest
    inputs:
      data: ${{parent.jobs.normalize_train.outputs.out}}

  merge_all:
    type: command
    component: azureml:merge_features@latest
    inputs:
      length: ${{parent.jobs.length_train.outputs.out}}
      sentiment: ${{parent.jobs.sentiment_train.outputs.out}}
      tfidf: ${{parent.jobs.tfidf.outputs.train_out}}
      sbert: ${{parent.jobs.sbert_train.outputs.out}}
